// Autogenerated by Frugal Compiler (3.17.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

// ignore_for_file: unused_import
// ignore_for_file: unused_field
import 'dart:typed_data' show Uint8List;

import 'package:collection/collection.dart';
import 'package:thrift/thrift.dart' as thrift;
import 'package:variety/variety.dart' as t_variety;
import 'package:actual_base_dart/actual_base_dart.dart' as t_actual_base_dart;
import 'package:intermediate_include/intermediate_include.dart' as t_intermediate_include;
import 'package:validStructs/validStructs.dart' as t_validStructs;
import 'package:ValidTypes/ValidTypes.dart' as t_ValidTypes;
import 'package:subdir_include_ns/subdir_include_ns.dart' as t_subdir_include_ns;

class EventWrapper implements thrift.TBase {
  static final thrift.TStruct _STRUCT_DESC = thrift.TStruct('EventWrapper');
  static final thrift.TField _ID_FIELD_DESC = thrift.TField('ID', thrift.TType.I64, 1);
  static final thrift.TField _EV_FIELD_DESC = thrift.TField('Ev', thrift.TType.STRUCT, 2);
  static final thrift.TField _EVENTS_FIELD_DESC = thrift.TField('Events', thrift.TType.LIST, 3);
  static final thrift.TField _EVENTS2_FIELD_DESC = thrift.TField('Events2', thrift.TType.SET, 4);
  static final thrift.TField _EVENT_MAP_FIELD_DESC = thrift.TField('EventMap', thrift.TType.MAP, 5);
  static final thrift.TField _NUMS_FIELD_DESC = thrift.TField('Nums', thrift.TType.LIST, 6);
  static final thrift.TField _ENUMS_FIELD_DESC = thrift.TField('Enums', thrift.TType.LIST, 7);
  static final thrift.TField _A_BOOL_FIELD_FIELD_DESC = thrift.TField('aBoolField', thrift.TType.BOOL, 8);
  static final thrift.TField _A_UNION_FIELD_DESC = thrift.TField('a_union', thrift.TType.STRUCT, 9);
  static final thrift.TField _TYPEDEF_OF_TYPEDEF_FIELD_DESC = thrift.TField('typedefOfTypedef', thrift.TType.STRING, 10);
  static final thrift.TField _DEPR_FIELD_DESC = thrift.TField('depr', thrift.TType.BOOL, 11);
  static final thrift.TField _DEPR_BINARY_FIELD_DESC = thrift.TField('deprBinary', thrift.TType.STRING, 12);
  static final thrift.TField _DEPR_LIST_FIELD_DESC = thrift.TField('deprList', thrift.TType.LIST, 13);
  static final thrift.TField _EVENTS_DEFAULT_FIELD_DESC = thrift.TField('EventsDefault', thrift.TType.LIST, 14);
  static final thrift.TField _EVENT_MAP_DEFAULT_FIELD_DESC = thrift.TField('EventMapDefault', thrift.TType.MAP, 15);
  static final thrift.TField _EVENT_SET_DEFAULT_FIELD_DESC = thrift.TField('EventSetDefault', thrift.TType.SET, 16);

  int iD;
  static const int ID = 1;
  t_variety.Event ev;
  static const int EV = 2;
  List<t_variety.Event> events;
  static const int EVENTS = 3;
  Set<t_variety.Event> events2;
  static const int EVENTS2 = 4;
  Map<int, t_variety.Event> eventMap;
  static const int EVENTMAP = 5;
  List<List<int>> nums;
  static const int NUMS = 6;
  List<int> enums;
  static const int ENUMS = 7;
  bool aBoolField;
  static const int ABOOLFIELD = 8;
  t_variety.TestingUnions a_union;
  static const int A_UNION = 9;
  String typedefOfTypedef;
  static const int TYPEDEFOFTYPEDEF = 10;
  /// This is a docstring comment for a deprecated field that has been spread
  /// across two lines.
  /// Deprecated: use something else
  @deprecated
  bool depr;
  static const int DEPR = 11;
  /// Deprecated: use something else
  @deprecated
  Uint8List deprBinary;
  static const int DEPRBINARY = 12;
  /// Deprecated: use something else
  @deprecated
  List<bool> deprList;
  static const int DEPRLIST = 13;
  List<t_variety.Event> eventsDefault = [
    ];
  static const int EVENTSDEFAULT = 14;
  Map<int, t_variety.Event> eventMapDefault = {
    };
  static const int EVENTMAPDEFAULT = 15;
  Set<t_variety.Event> eventSetDefault = Set<t_variety.Event>.from([
    ]);
  static const int EVENTSETDEFAULT = 16;


  bool isSetID() => this.iD != null;

  unsetID() {
    this.iD = null;
  }

  bool isSetEv() => this.ev != null;

  unsetEv() {
    this.ev = null;
  }

  bool isSetEvents() => this.events != null;

  unsetEvents() {
    this.events = null;
  }

  bool isSetEvents2() => this.events2 != null;

  unsetEvents2() {
    this.events2 = null;
  }

  bool isSetEventMap() => this.eventMap != null;

  unsetEventMap() {
    this.eventMap = null;
  }

  bool isSetNums() => this.nums != null;

  unsetNums() {
    this.nums = null;
  }

  bool isSetEnums() => this.enums != null;

  unsetEnums() {
    this.enums = null;
  }

  bool isSetABoolField() => this.aBoolField != null;

  unsetABoolField() {
    this.aBoolField = null;
  }

  bool isSetA_union() => this.a_union != null;

  unsetA_union() {
    this.a_union = null;
  }

  bool isSetTypedefOfTypedef() => this.typedefOfTypedef != null;

  unsetTypedefOfTypedef() {
    this.typedefOfTypedef = null;
  }

  @deprecated  bool isSetDepr() => this.depr != null;

  unsetDepr() {
    // ignore: deprecated_member_use
    this.depr = null;
  }

  @deprecated  bool isSetDeprBinary() => this.deprBinary != null;

  unsetDeprBinary() {
    // ignore: deprecated_member_use
    this.deprBinary = null;
  }

  @deprecated  bool isSetDeprList() => this.deprList != null;

  unsetDeprList() {
    // ignore: deprecated_member_use
    this.deprList = null;
  }

  bool isSetEventsDefault() => this.eventsDefault != null;

  unsetEventsDefault() {
    this.eventsDefault = null;
  }

  bool isSetEventMapDefault() => this.eventMapDefault != null;

  unsetEventMapDefault() {
    this.eventMapDefault = null;
  }

  bool isSetEventSetDefault() => this.eventSetDefault != null;

  unsetEventSetDefault() {
    this.eventSetDefault = null;
  }

  @override
  getFieldValue(int fieldID) {
    switch (fieldID) {
      case ID:
        return this.iD;
      case EV:
        return this.ev;
      case EVENTS:
        return this.events;
      case EVENTS2:
        return this.events2;
      case EVENTMAP:
        return this.eventMap;
      case NUMS:
        return this.nums;
      case ENUMS:
        return this.enums;
      case ABOOLFIELD:
        return this.aBoolField;
      case A_UNION:
        return this.a_union;
      case TYPEDEFOFTYPEDEF:
        return this.typedefOfTypedef;
      case DEPR:
        // ignore: deprecated_member_use
        return this.depr;
      case DEPRBINARY:
        // ignore: deprecated_member_use
        return this.deprBinary;
      case DEPRLIST:
        // ignore: deprecated_member_use
        return this.deprList;
      case EVENTSDEFAULT:
        return this.eventsDefault;
      case EVENTMAPDEFAULT:
        return this.eventMapDefault;
      case EVENTSETDEFAULT:
        return this.eventSetDefault;
      default:
        throw ArgumentError("Field $fieldID doesn't exist!");
    }
  }

  @override
  setFieldValue(int fieldID, Object value) {
    switch (fieldID) {
      case ID:
        this.iD = value as int;
        break;

      case EV:
        this.ev = value as t_variety.Event;
        break;

      case EVENTS:
        this.events = value as List<t_variety.Event>;
        break;

      case EVENTS2:
        this.events2 = value as Set<t_variety.Event>;
        break;

      case EVENTMAP:
        this.eventMap = value as Map<int, t_variety.Event>;
        break;

      case NUMS:
        this.nums = value as List<List<int>>;
        break;

      case ENUMS:
        this.enums = value as List<int>;
        break;

      case ABOOLFIELD:
        this.aBoolField = value as bool;
        break;

      case A_UNION:
        this.a_union = value as t_variety.TestingUnions;
        break;

      case TYPEDEFOFTYPEDEF:
        this.typedefOfTypedef = value as String;
        break;

      case DEPR:
        // ignore: deprecated_member_use
        this.depr = value as bool;
        break;

      case DEPRBINARY:
        // ignore: deprecated_member_use
        this.deprBinary = value as Uint8List;
        break;

      case DEPRLIST:
        // ignore: deprecated_member_use
        this.deprList = value as List<bool>;
        break;

      case EVENTSDEFAULT:
        this.eventsDefault = value as List<t_variety.Event>;
        break;

      case EVENTMAPDEFAULT:
        this.eventMapDefault = value as Map<int, t_variety.Event>;
        break;

      case EVENTSETDEFAULT:
        this.eventSetDefault = value as Set<t_variety.Event>;
        break;

      default:
        throw ArgumentError("Field $fieldID doesn't exist!");
    }
  }

  // Returns true if the field corresponding to fieldID is set (has been assigned a value) and false otherwise
  @override
  bool isSet(int fieldID) {
    return getFieldValue(fieldID) != null;
  }

  @override
  read(thrift.TProtocol iprot) {
    iprot.readStructBegin();
    for (thrift.TField field = iprot.readFieldBegin();
        field.type != thrift.TType.STOP;
        field = iprot.readFieldBegin()) {
      switch (field.id) {
        case ID:
          if (field.type == thrift.TType.I64) {
            this.iD = iprot.readI64();
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case EV:
          if (field.type == thrift.TType.STRUCT) {
            final elem53 = t_variety.Event();
            this.ev = elem53;
            elem53.read(iprot);
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case EVENTS:
          if (field.type == thrift.TType.LIST) {
            thrift.TList elem54 = iprot.readListBegin();
            final elem58 = <t_variety.Event>[];
            for(int elem57 = 0; elem57 < elem54.length; ++elem57) {
              final elem56 = t_variety.Event();
              t_variety.Event elem55 = elem56;
              elem56.read(iprot);
              elem58.add(elem55);
            }
            iprot.readListEnd();
            this.events = elem58;
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case EVENTS2:
          if (field.type == thrift.TType.SET) {
            thrift.TSet elem59 = iprot.readSetBegin();
            final elem63 = <t_variety.Event>{};
            for(int elem62 = 0; elem62 < elem59.length; ++elem62) {
              final elem61 = t_variety.Event();
              t_variety.Event elem60 = elem61;
              elem61.read(iprot);
              elem63.add(elem60);
            }
            iprot.readSetEnd();
            this.events2 = elem63;
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case EVENTMAP:
          if (field.type == thrift.TType.MAP) {
            thrift.TMap elem64 = iprot.readMapBegin();
            final elem68 = <int, t_variety.Event>{};
            for(int elem67 = 0; elem67 < elem64.length; ++elem67) {
              int elem69 = iprot.readI64();
              final elem66 = t_variety.Event();
              t_variety.Event elem65 = elem66;
              elem66.read(iprot);
              elem68[elem69] = elem65;
            }
            iprot.readMapEnd();
            this.eventMap = elem68;
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case NUMS:
          if (field.type == thrift.TType.LIST) {
            thrift.TList elem70 = iprot.readListBegin();
            final elem76 = <List<int>>[];
            for(int elem75 = 0; elem75 < elem70.length; ++elem75) {
              thrift.TList elem72 = iprot.readListBegin();
              final elem71 = <int>[];
              for(int elem74 = 0; elem74 < elem72.length; ++elem74) {
                int elem73 = iprot.readI32();
                elem71.add(elem73);
              }
              iprot.readListEnd();
              elem76.add(elem71);
            }
            iprot.readListEnd();
            this.nums = elem76;
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case ENUMS:
          if (field.type == thrift.TType.LIST) {
            thrift.TList elem77 = iprot.readListBegin();
            final elem80 = <int>[];
            for(int elem79 = 0; elem79 < elem77.length; ++elem79) {
              int elem78 = iprot.readI32();
              elem80.add(elem78);
            }
            iprot.readListEnd();
            this.enums = elem80;
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case ABOOLFIELD:
          if (field.type == thrift.TType.BOOL) {
            this.aBoolField = iprot.readBool();
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case A_UNION:
          if (field.type == thrift.TType.STRUCT) {
            final elem81 = t_variety.TestingUnions();
            this.a_union = elem81;
            elem81.read(iprot);
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case TYPEDEFOFTYPEDEF:
          if (field.type == thrift.TType.STRING) {
            this.typedefOfTypedef = iprot.readString();
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case DEPR:
          if (field.type == thrift.TType.BOOL) {
            // ignore: deprecated_member_use
            this.depr = iprot.readBool();
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case DEPRBINARY:
          if (field.type == thrift.TType.STRING) {
            // ignore: deprecated_member_use
            this.deprBinary = iprot.readBinary();
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case DEPRLIST:
          if (field.type == thrift.TType.LIST) {
            thrift.TList elem82 = iprot.readListBegin();
            // ignore: deprecated_member_use
            final elem85 = <bool>[];
            for(int elem84 = 0; elem84 < elem82.length; ++elem84) {
              bool elem83 = iprot.readBool();
              // ignore: deprecated_member_use
              elem85.add(elem83);
            }
            iprot.readListEnd();
            this.deprList = elem85;
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case EVENTSDEFAULT:
          if (field.type == thrift.TType.LIST) {
            thrift.TList elem86 = iprot.readListBegin();
            final elem90 = <t_variety.Event>[];
            for(int elem89 = 0; elem89 < elem86.length; ++elem89) {
              final elem88 = t_variety.Event();
              t_variety.Event elem87 = elem88;
              elem88.read(iprot);
              elem90.add(elem87);
            }
            iprot.readListEnd();
            this.eventsDefault = elem90;
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case EVENTMAPDEFAULT:
          if (field.type == thrift.TType.MAP) {
            thrift.TMap elem91 = iprot.readMapBegin();
            final elem95 = <int, t_variety.Event>{};
            for(int elem94 = 0; elem94 < elem91.length; ++elem94) {
              int elem96 = iprot.readI64();
              final elem93 = t_variety.Event();
              t_variety.Event elem92 = elem93;
              elem93.read(iprot);
              elem95[elem96] = elem92;
            }
            iprot.readMapEnd();
            this.eventMapDefault = elem95;
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case EVENTSETDEFAULT:
          if (field.type == thrift.TType.SET) {
            thrift.TSet elem97 = iprot.readSetBegin();
            final elem101 = <t_variety.Event>{};
            for(int elem100 = 0; elem100 < elem97.length; ++elem100) {
              final elem99 = t_variety.Event();
              t_variety.Event elem98 = elem99;
              elem99.read(iprot);
              elem101.add(elem98);
            }
            iprot.readSetEnd();
            this.eventSetDefault = elem101;
          } else {
            thrift.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          thrift.TProtocolUtil.skip(iprot, field.type);
          break;
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    validate();
  }

  @override
  write(thrift.TProtocol oprot) {
    validate();

    oprot.writeStructBegin(_STRUCT_DESC);
    final elem102 = iD;
    if (isSetID()) {
      oprot.writeFieldBegin(_ID_FIELD_DESC);
      oprot.writeI64(elem102);
      oprot.writeFieldEnd();
    }
    final elem103 = ev;
    oprot.writeFieldBegin(_EV_FIELD_DESC);
    elem103.write(oprot);
    oprot.writeFieldEnd();
    final elem104 = events;
    if (isSetEvents()) {
      oprot.writeFieldBegin(_EVENTS_FIELD_DESC);
      oprot.writeListBegin(thrift.TList(thrift.TType.STRUCT, elem104.length));
      for(var elem105 in elem104) {
        elem105.write(oprot);
      }
      oprot.writeListEnd();
      oprot.writeFieldEnd();
    }
    final elem106 = events2;
    if (isSetEvents2()) {
      oprot.writeFieldBegin(_EVENTS2_FIELD_DESC);
      oprot.writeSetBegin(thrift.TSet(thrift.TType.STRUCT, elem106.length));
      for(var elem107 in elem106) {
        elem107.write(oprot);
      }
      oprot.writeSetEnd();
      oprot.writeFieldEnd();
    }
    final elem108 = eventMap;
    if (isSetEventMap()) {
      oprot.writeFieldBegin(_EVENT_MAP_FIELD_DESC);
      oprot.writeMapBegin(thrift.TMap(thrift.TType.I64, thrift.TType.STRUCT, elem108.length));
      for(var elem109 in elem108.keys) {
        final elem110 = elem108[elem109];
        oprot.writeI64(elem109);
        elem110.write(oprot);
      }
      oprot.writeMapEnd();
      oprot.writeFieldEnd();
    }
    final elem111 = nums;
    if (isSetNums()) {
      oprot.writeFieldBegin(_NUMS_FIELD_DESC);
      oprot.writeListBegin(thrift.TList(thrift.TType.LIST, elem111.length));
      for(var elem112 in elem111) {
        oprot.writeListBegin(thrift.TList(thrift.TType.I32, elem112.length));
        for(var elem113 in elem112) {
          oprot.writeI32(elem113);
        }
        oprot.writeListEnd();
      }
      oprot.writeListEnd();
      oprot.writeFieldEnd();
    }
    final elem114 = enums;
    if (isSetEnums()) {
      oprot.writeFieldBegin(_ENUMS_FIELD_DESC);
      oprot.writeListBegin(thrift.TList(thrift.TType.I32, elem114.length));
      for(var elem115 in elem114) {
        oprot.writeI32(elem115);
      }
      oprot.writeListEnd();
      oprot.writeFieldEnd();
    }
    final elem116 = aBoolField;
    oprot.writeFieldBegin(_A_BOOL_FIELD_FIELD_DESC);
    oprot.writeBool(elem116);
    oprot.writeFieldEnd();
    final elem117 = a_union;
    if (isSetA_union()) {
      oprot.writeFieldBegin(_A_UNION_FIELD_DESC);
      elem117.write(oprot);
      oprot.writeFieldEnd();
    }
    final elem118 = typedefOfTypedef;
    if (isSetTypedefOfTypedef()) {
      oprot.writeFieldBegin(_TYPEDEF_OF_TYPEDEF_FIELD_DESC);
      oprot.writeString(elem118);
      oprot.writeFieldEnd();
    }
    final elem119 = depr;
    oprot.writeFieldBegin(_DEPR_FIELD_DESC);
    oprot.writeBool(elem119);
    oprot.writeFieldEnd();
    final elem120 = deprBinary;
    // ignore: deprecated_member_use
    if (isSetDeprBinary()) {
      oprot.writeFieldBegin(_DEPR_BINARY_FIELD_DESC);
      oprot.writeBinary(elem120);
      oprot.writeFieldEnd();
    }
    final elem121 = deprList;
    // ignore: deprecated_member_use
    if (isSetDeprList()) {
      oprot.writeFieldBegin(_DEPR_LIST_FIELD_DESC);
      oprot.writeListBegin(thrift.TList(thrift.TType.BOOL, elem121.length));
      for(var elem122 in elem121) {
        oprot.writeBool(elem122);
      }
      oprot.writeListEnd();
      oprot.writeFieldEnd();
    }
    final elem123 = eventsDefault;
    if (isSetEventsDefault()) {
      oprot.writeFieldBegin(_EVENTS_DEFAULT_FIELD_DESC);
      oprot.writeListBegin(thrift.TList(thrift.TType.STRUCT, elem123.length));
      for(var elem124 in elem123) {
        elem124.write(oprot);
      }
      oprot.writeListEnd();
      oprot.writeFieldEnd();
    }
    final elem125 = eventMapDefault;
    if (isSetEventMapDefault()) {
      oprot.writeFieldBegin(_EVENT_MAP_DEFAULT_FIELD_DESC);
      oprot.writeMapBegin(thrift.TMap(thrift.TType.I64, thrift.TType.STRUCT, elem125.length));
      for(var elem126 in elem125.keys) {
        final elem127 = elem125[elem126];
        oprot.writeI64(elem126);
        elem127.write(oprot);
      }
      oprot.writeMapEnd();
      oprot.writeFieldEnd();
    }
    final elem128 = eventSetDefault;
    if (isSetEventSetDefault()) {
      oprot.writeFieldBegin(_EVENT_SET_DEFAULT_FIELD_DESC);
      oprot.writeSetBegin(thrift.TSet(thrift.TType.STRUCT, elem128.length));
      for(var elem129 in elem128) {
        elem129.write(oprot);
      }
      oprot.writeSetEnd();
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @override
  String toString() {
    StringBuffer ret = StringBuffer('EventWrapper(');

    if (isSetID()) {
      ret.write('iD:');
      ret.write(this.iD);
    }

    ret.write(', ');
    ret.write('ev:');
    if (this.ev == null) {
      ret.write('null');
    } else {
      ret.write(this.ev);
    }

    ret.write(', ');
    ret.write('events:');
    if (this.events == null) {
      ret.write('null');
    } else {
      ret.write(this.events);
    }

    ret.write(', ');
    ret.write('events2:');
    if (this.events2 == null) {
      ret.write('null');
    } else {
      ret.write(this.events2);
    }

    ret.write(', ');
    ret.write('eventMap:');
    if (this.eventMap == null) {
      ret.write('null');
    } else {
      ret.write(this.eventMap);
    }

    ret.write(', ');
    ret.write('nums:');
    if (this.nums == null) {
      ret.write('null');
    } else {
      ret.write(this.nums);
    }

    ret.write(', ');
    ret.write('enums:');
    if (this.enums == null) {
      ret.write('null');
    } else {
      ret.write(this.enums);
    }

    ret.write(', ');
    ret.write('aBoolField:');
    ret.write(this.aBoolField);

    ret.write(', ');
    ret.write('a_union:');
    if (this.a_union == null) {
      ret.write('null');
    } else {
      ret.write(this.a_union);
    }

    ret.write(', ');
    ret.write('typedefOfTypedef:');
    if (this.typedefOfTypedef == null) {
      ret.write('null');
    } else {
      ret.write(this.typedefOfTypedef);
    }

    ret.write(', ');
    ret.write('depr:');
    // ignore: deprecated_member_use
    ret.write(this.depr);

    ret.write(', ');
    ret.write('deprBinary:');
    // ignore: deprecated_member_use
    if (this.deprBinary == null) {
      ret.write('null');
    } else {
      ret.write('BINARY');
    }

    ret.write(', ');
    ret.write('deprList:');
    // ignore: deprecated_member_use
    if (this.deprList == null) {
      ret.write('null');
    } else {
      // ignore: deprecated_member_use
      ret.write(this.deprList);
    }

    if (isSetEventsDefault()) {
      ret.write(', ');
      ret.write('eventsDefault:');
      if (this.eventsDefault == null) {
        ret.write('null');
      } else {
        ret.write(this.eventsDefault);
      }
    }

    if (isSetEventMapDefault()) {
      ret.write(', ');
      ret.write('eventMapDefault:');
      if (this.eventMapDefault == null) {
        ret.write('null');
      } else {
        ret.write(this.eventMapDefault);
      }
    }

    if (isSetEventSetDefault()) {
      ret.write(', ');
      ret.write('eventSetDefault:');
      if (this.eventSetDefault == null) {
        ret.write('null');
      } else {
        ret.write(this.eventSetDefault);
      }
    }

    ret.write(')');

    return ret.toString();
  }

  @override
  bool operator ==(Object o) {
    if (o is EventWrapper) {
      return this.iD == o.iD &&
        this.ev == o.ev &&
        DeepCollectionEquality().equals(this.events, o.events) &&
        DeepCollectionEquality().equals(this.events2, o.events2) &&
        DeepCollectionEquality().equals(this.eventMap, o.eventMap) &&
        DeepCollectionEquality().equals(this.nums, o.nums) &&
        DeepCollectionEquality().equals(this.enums, o.enums) &&
        this.aBoolField == o.aBoolField &&
        this.a_union == o.a_union &&
        this.typedefOfTypedef == o.typedefOfTypedef &&
        // ignore: deprecated_member_use
        this.depr == o.depr &&
        // ignore: deprecated_member_use
        this.deprBinary == o.deprBinary &&
        // ignore: deprecated_member_use
        DeepCollectionEquality().equals(this.deprList, o.deprList) &&
        DeepCollectionEquality().equals(this.eventsDefault, o.eventsDefault) &&
        DeepCollectionEquality().equals(this.eventMapDefault, o.eventMapDefault) &&
        DeepCollectionEquality().equals(this.eventSetDefault, o.eventSetDefault);
    }
    return false;
  }

  @override
  int get hashCode {
    var value = 17;
    value = (value * 31) ^ this.iD.hashCode;
    value = (value * 31) ^ this.ev.hashCode;
    value = (value * 31) ^ DeepCollectionEquality().hash(this.events);
    value = (value * 31) ^ DeepCollectionEquality().hash(this.events2);
    value = (value * 31) ^ DeepCollectionEquality().hash(this.eventMap);
    value = (value * 31) ^ DeepCollectionEquality().hash(this.nums);
    value = (value * 31) ^ DeepCollectionEquality().hash(this.enums);
    value = (value * 31) ^ this.aBoolField.hashCode;
    value = (value * 31) ^ this.a_union.hashCode;
    value = (value * 31) ^ this.typedefOfTypedef.hashCode;
    // ignore: deprecated_member_use
    value = (value * 31) ^ this.depr.hashCode;
    // ignore: deprecated_member_use
    value = (value * 31) ^ this.deprBinary.hashCode;
    // ignore: deprecated_member_use
    value = (value * 31) ^ DeepCollectionEquality().hash(this.deprList);
    value = (value * 31) ^ DeepCollectionEquality().hash(this.eventsDefault);
    value = (value * 31) ^ DeepCollectionEquality().hash(this.eventMapDefault);
    value = (value * 31) ^ DeepCollectionEquality().hash(this.eventSetDefault);
    return value;
  }

  EventWrapper clone({
    int iD,
    t_variety.Event ev,
    List<t_variety.Event> events,
    Set<t_variety.Event> events2,
    Map<int, t_variety.Event> eventMap,
    List<List<int>> nums,
    List<int> enums,
    bool aBoolField,
    t_variety.TestingUnions a_union,
    String typedefOfTypedef,
    // ignore: deprecated_member_use
    bool depr,
    // ignore: deprecated_member_use
    Uint8List deprBinary,
    // ignore: deprecated_member_use
    List<bool> deprList,
    List<t_variety.Event> eventsDefault,
    Map<int, t_variety.Event> eventMapDefault,
    Set<t_variety.Event> eventSetDefault,
  }) {
    return EventWrapper()
      ..iD = iD ?? this.iD
      ..ev = ev ?? this.ev
      ..events = events ?? this.events
      ..events2 = events2 ?? this.events2
      ..eventMap = eventMap ?? this.eventMap
      ..nums = nums ?? this.nums
      ..enums = enums ?? this.enums
      ..aBoolField = aBoolField ?? this.aBoolField
      ..a_union = a_union ?? this.a_union
      ..typedefOfTypedef = typedefOfTypedef ?? this.typedefOfTypedef
      // ignore: deprecated_member_use
      ..depr = depr ?? this.depr
      // ignore: deprecated_member_use
      ..deprBinary = deprBinary ?? this.deprBinary
      // ignore: deprecated_member_use
      ..deprList = deprList ?? this.deprList
      ..eventsDefault = eventsDefault ?? this.eventsDefault
      ..eventMapDefault = eventMapDefault ?? this.eventMapDefault
      ..eventSetDefault = eventSetDefault ?? this.eventSetDefault;
  }

  validate() {
    // check for required fields
    if (this.ev == null) {
      throw thrift.TProtocolError(thrift.TProtocolErrorType.INVALID_DATA, "Required field 'ev' was not present in struct EventWrapper");
    }
  }
}
